baseURL = 'https://blog.okello.io'
languageCode = 'en-us'
title = 'Recursive Heuristics'
# theme = 'hugo-blog-awesome'
theme = 'hugo-theme-gruvbox'

[build]
    # The theme enables writeStats which is required for PurgeCSS
    _merge = "deep"

[params]
    enableTagCloud = true
    author = "Teddy Okello"
    description = "A collection of tutorials, notes and my thoughts on various topics"
    [params.logo]
        text = "RH"
        url = "/"
    [params.prism]
        languages = ["markup", "css", "clike", "javascript", "go", "python"]
        plugins = ["normalize-whitespace", "toolbar", "copy-to-clipboard"]

[module]
    [[module.imports]]
        path = "github.com/schnerring/hugo-mod-json-resume"
        [[module.imports.mounts]]
            source = "data"
            target = "data"
        [[module.imports.mounts]]
            source = "layouts"
            target = "layouts"
        [[module.imports.mounts]]
            source = "assets/css/json-resume.css"
            target = "assets/css/critical/44-json-resume.css"
[[module.mounts]]
    # required by hugo-mod-json-resume
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"
[[module.mounts]]
    source = "assets"
    target = "assets"
[[module.mounts]]
    source = "layouts"
    target = "layouts"
[[module.mounts]]
    source = "static"
    target = "static"
[[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
[[module.mounts]]
    source = "node_modules/prism-themes/themes"
    target = "assets/prism-themes"
[[module.mounts]]
    source = "node_modules/typeface-fira-code/files"
    target = "static/fonts"
[[module.mounts]]
    source = "node_modules/typeface-roboto-slab/files"
    target = "static/fonts"
[[module.mounts]]
    source = "node_modules/@tabler/icons/icons"
    target = "assets/tabler-icons"


[menu]
    [[menu.main]]
        identifier = "tutorials"
        name = "How-To"
        pageRef = "/tutorials"
        weight = 1
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "https://okello.io"
        weight = 3
